### ISSUE TITLE
Pick a logo for ckb-js org

### ISSUE THREAD

**Issue by Keith-CY** [ckb-js/topics#3]
The first batch of logo drafts has been updated in Figma(https://www.figma.com/file/6XNoimRDbFTTNm016rbIdU/Magickbase?node-id=4531%3A22158)

Preview:
![image](https://user-images.githubusercontent.com/7271329/187503169-da3866d1-ddb8-4569-8dc1-16b9f54b3a02.png)

These 6 are just drafts and will be updated with feedback

**Comment by Keith-CY** [comment]
Personally speaking, I would pick one from the 4, 5, 6 as our logo.

The 4. is kinda modern with subtle 3d visual effects
![image](https://user-images.githubusercontent.com/7271329/187504193-87b6ad0c-eca5-45a0-9abe-bb258078d1c3.png)

The 5. reminds me of the logo of NeXT plus Microsoft, representing Art plus Engineering respectively
![image](https://user-images.githubusercontent.com/7271329/187505654-c837e4fa-cf4d-4aee-a2e8-5a12b83cb2ae.png)

The 6. is direct, neat, and cute
![image](https://user-images.githubusercontent.com/7271329/187505933-9479527f-b2be-4a65-95da-7f6f8f846e0c.png)
and quite close to a classic javascript logo
![image](https://user-images.githubusercontent.com/7271329/187506396-7f59d885-2e8d-44e4-9e5f-fa8a362e8cc6.png)

**Comment by janx** [comment]
Thanks for inviting, all versions look awesome!

1 vote for 6th, it's cute.

**Comment by Keith-CY** [comment]
> I have a little confused about the right part of the 6th. I vote for 5th, it's direct

I think it's a cup of wine, which makes the logo a bit cute. And as the description says, the group of ckb and js will brew something fragrant.

**Comment by linkdesu** [comment]
I vote for the 5th and the 6th. ⏫

A logo for a library is not required, and developers will probably not notice it at first. That's why I think clarity of meaning is most important. And both the 5th and the 6th seem straight forward.

**Comment by yanguoyu** [comment]
> > I have a little confused about the right part of the 6th. I vote for 5th, it's direct
> 
> I think it's a cup of wine, which makes the logo a bit cute. And as the description says, the group of ckb + js will brew something fragrant.

It's great. I also vote for 6th. Direct, simple, cute.

**Comment by homura** [comment]
vote for 5th 

one reason is that ckb-js is probably like a toolbox with a bunch of tools, and another reason is that we often liken a `Cell` to a `Box`

**Comment by yanguoyu** [comment]
vote for 6

**Comment by Keith-CY** [comment]
Hi there, if no more feedback comes by 09/16, let's freeze the voting and make a final choice.

Current state:
- 5: @linkdesu @homura 
- 6: @janx @linkdesu @yanguoyu @Keith-CY 
- 9: @Keith-CY

**Comment by Kirl70** [comment]
LOGO file, which contains a transparent background and white background png format and ico format files.

[CKB-JS LOGO.zip](https://github.com/ckb-js/topics/files/9632303/CKB-JS.LOGO.zip)
